### ISSUE TITLE
Redux Plugin Activation Error

### ISSUE THREAD

**Issue by spointecker** [reduxframework/redux-framework#3675]
Hi, 

I am currently getting the following fatal error when activating the redux plugin in wordpress:
```
Fatal error: Uncaught Error: [] operator not supported for strings in /home/www/wordpress/wp-content/plugins/redux-framework/class.redux-plugin.php:314 Stack trace: #0 /home/www/wordpress/wp-content/plugins/redux-framework/class.redux-plugin.php(227): ReduxFrameworkPlugin::single_activate() #1 /home/www/wordpress/wp-includes/class-wp-hook.php(286): ReduxFrameworkPlugin::activate('') #2 /home/www/wordpress/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #3 /home/www/wordpress/wp-includes/plugin.php(465): WP_Hook->do_action(Array) #4 /home/www/wordpress/wp-admin/plugins.php(177): do_action('activate_redux-...') #5 {main} thrown in /home/www/wordpress/wp-content/plugins/redux-framework/class.redux-plugin.php on line 314
```

I am posting this here because the error comes directly from the plugin code. If I am still wrong here please don´t hesitate to tell me ;-)

Wordpress 5.2.3 running on PHP 7.2

**Comment by spointecker** [comment]
I am guessing it´s related to https://wordpress.org/support/topic/got-this-error/

**Comment by spointecker** [comment]
Problem is the PHP version, if it‘s 7.1+ it cannot be activated!
This lead me to the solution: https://wordpress.org/support/topic/i-cant-activate-the-plugin-on-my-site/
